package ExceptionHandling;

import java.io.IOException;

public class P03 {
    public static void main(String[] args) {

        try{

        }
//        catch(ArithmeticException e)
//        {
//            System.out.println("from catch block");
//        }
//        catch (ArrayIndexOutOfBoundsException e)
//        {
//
//        }
//        catch (IndexOutOfBoundsException e)
//        {
//
//        }
        catch (Exception e)
        {

        }
    }
}
